const logIn = 'Log In';
const password = 'Password';
const emailAddress = 'Email Address';
const forgottenPassword = 'Forgotten Password?';
const needAnAccount = 'Need an Account?';
const myProfile = 'My Profile';
const settings = 'Settings';
const help = 'Help';
const socialValueScoreText = 'Social Value Score';
const privacyCentre = 'Privacy Centre';
const termsConditions = 'Terms & Conditions';
const memberSinceText = 'Member Since Feb 2022';
const welComeText = 'Welcome to your Social Value Hub';
const companyNameText = '[Company Name]’s';
const treeText = '65 Trees';
const exploreText = 'Explore';
const accessNow = 'Access Now ';
const dashboard = 'Dashboard';
const mindfulness = 'Mindfulness';
const yogaVideos = 'Yoga Videos';
const brainGames = 'Brain Games';
const mentalhealthapp = 'Mental Health App';
const wellbeing = 'Wellbeing';
const Planet = 'Planet';
const community = 'Community';
const finances = 'Finances';
const myPhysicalHealth = 'My Physical Health';
const myMentalHealth = 'My Mental Health';
const more = 'More';
const support = 'Support';
const discountCard = 'Discount Card';
const insuranceQuotes = 'Insurance Quotes';
const ukBased =
    'As an SVC member you have helped the following UK based Charities';
const articles = 'Articles';
const dailyWorkouts = 'Daily Workouts';
const mealPlans = 'Meal Plans';
const bmiCalculator = 'BMI Calculator';
const lesMills = 'Les Mills';
const maximumMemberShipText = 'Learn how to maximise your membership';
const memberShipText = 'Get You Free XO Discount Card membership';
const wellbeingHub = 'Wellbeing Hub ';
const memberShipDesc =
    'Get access to 100 s of discounts from some of the UK s biggest and best retailers. Free XO Discounts membership is included in your SVC membership.';
const wellbeingHubText =
    'Information, advice and guidence to improve your physical, mental and financial wellbeing';
const soFarYouHaveHelpedPlantText = 'So far you have helped plant:';
const lesmillsText =
    'Discover Les Mills Workouts with 200+ training videos. Workout at home or on the go!';
